### ISSUE TITLE
[BUG] wasmcloud provider wit bindgen fails to export interfaces

### ISSUE THREAD

**Issue by LUK3ARK** [wasmCloud/wasmCloud#1597]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [X] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

When i use the following custom sql interface:
```wit

interface types {
    /// one single row item
    record row {
        fields: list<field-value>,
    }

    record field-value {
        field-name: string,
        value: data-type,
    }
    
    /// common data types
    variant data-type {
        int32(s32),
        int64(s64),
        uint32(u32),
        uint64(u64),
        float(float64),
        double(float64),
        str(string),
        boolean(bool),
        date(string),
        time(string),
        timestamp(string),
        binary(list<u8>),
        null
    }

    /// allows parameterized queries
    /// e.g., prepare("SELECT * FROM users WHERE name = ? AND age = ?", vec!["John Doe", "32"])
    resource statement {
        prepare: static func(query: string, params: list<string>) -> result<statement, error>;
    }
    /// An error resource type.
    /// Currently, this provides only one function to return a string representation
    /// of the error. In the future, this will be extended to provide more information.
    resource error {
		trace: func() -> string;
  	}
    
    /// A connection to a sql store.
    resource connection {
        open: static func(name: string) -> result<connection, error>;
    }
}
```

I am unable to compile my provider as I get this error:

|
   = help: message: `"static_statement.prepare"` is not a valid identifier

### Steps to reproduce

1. Reproduce wasi:sql with new custom interface
2. Create example provider
3. wit-bindgen = { version = "0.19.2", features = ["default"] }
4. wasmcloud-provider-wit-bindgen = { git = "https://github.com/wasmCloud/wasmCloud.git", branch = "main" }

### Expected behavior

Expect for my wit to be generated

### Environment

- OS: Mac

### Screenshots / Logs / Additional context

<img width="530" alt="image" src="https://github.com/wasmCloud/wasmCloud/assets/79220359/87536209-b357-4adf-ac3d-5b590a7298c1">

**Comment by LUK3ARK** [comment]
This is the only error that i receive from the macro it seems so, however this isn't the only case. If i try to depend on wasi:logging instead of my custom port of wasi:sql which is very similar and I doubt is problematic (it works for all of my actors that depend on the same WIT)  and remove all dependencies and only import wasi:logging in my final world for my provider like so:


world provider-my-world {
    import wasi:logging/logging;
    export my-world-provider-interface;
}

then i get this error:
help: message: failed to translate export fn: unsupported type kind TypeDef {
               name: Some(
                   "level",
               ),
               kind: Enum(
                   Enum {
                       cases: [
                           EnumCase {
                               name: "trace",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages about the values of variables and the flow of\ncontrol within a program.",
                                   ),
                               },
                           },
                           EnumCase {
                               name: "debug",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages likely to be of interest to someone debugging a\nprogram.",
                                   ),
                               },
                           },
                           EnumCase {
                               name: "info",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages likely to be of interest to someone monitoring a\nprogram.",
                                   ),
                               },
                           },
                           EnumCase {
                               name: "warn",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages indicating hazardous situations.",
                                   ),
                               },
                           },
                           EnumCase {
                               name: "error",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages indicating serious errors.",
                                   ),
                               },
                           },
                           EnumCase {
                               name: "critical",
                               docs: Docs {
                                   contents: Some(
                                       "Describes messages indicating fatal errors.",
                                   ),
                               },
                           },
                       ],
                   },
               ),
               owner: Interface(
                   Id {
                       idx: 0,
                   },
               ),
               docs: Docs {
                   contents: Some(
                       "A log level, describing a kind of message.",
                   ),
               },
           }
           
           
           
   So the provider bindgen then starts complaining about the logging WIT

**Comment by wbaileyisla** [comment]
Any updates here?

**Comment by vados-cosmonic** [comment]
Hey @wbaileyisla did you run into the same issue? Would you mind sharing a reproduction? 

@LUK3ARK Resource support is lacking in provider bindgen right now -- I assume that the thing you're trying to implement *must* use a resource, is that correct?

**Comment by LUK3ARK** [comment]
I am just trying to get the macro to compile, yes please refer to sql here:

```wit

    /// allows parameterized queries
    /// e.g., prepare("SELECT * FROM users WHERE name = ? AND age = ?", vec!["John Doe", "32"])
    resource statement {
        prepare: static func(query: string, params: list<string>) -> result<statement, error>;
    }
    /// An error resource type.
    /// Currently, this provides only one function to return a string representation
    /// of the error. In the future, this will be extended to provide more information.
    resource error {
		trace: func() -> string;
  	}
    
    /// A connection to a sql store.
    resource connection {
        open: static func(name: string) -> result<connection, error>;
    }


```

**Comment by LUK3ARK** [comment]
I also have a custom sql provider that I cannot use because of this error. Currently blocked heavily on this.

please see the world definition:

```wit
package lattica:provider-sql;

world provider-sql-client {
    export org:sql/readwrite@0.1.0;
}

interface readwrite {
    use types.{statement, row, error, connection};
    
    /// query is optimized for querying data, and 
    /// implementors can make use of that fact to optimize 
    /// the performance of query execution (e.g., using
    /// indexes).
    query: func(c: borrow<connection>, q: borrow<statement>) -> result<list<row>, error>;
    
    /// exec is for modifying data in the database.
    exec: func(c: borrow<connection>, q: borrow<statement>) -> result<u32, error>;
}

interface types {
    /// one single row item
    record row {
        fields: list<field-value>,
    }

    record field-value {
        field-name: string,
        value: data-type,
    }
    
    /// common data types
    variant data-type {
        int32(s32),
        int64(s64),
        uint32(u32),
        uint64(u64),
        float(float64),
        double(float64),
        str(string),
        boolean(bool),
        date(string),
        time(string),
        timestamp(string),
        binary(list<u8>),
        null
    }

    /// allows parameterized queries
    /// e.g., prepare("SELECT * FROM users WHERE name = ? AND age = ?", vec!["John Doe", "32"])
    resource statement {
        prepare: static func(query: string, params: list<string>) -> result<statement, error>;
    }
    /// An error resource type.
    /// Currently, this provides only one function to return a string representation
    /// of the error. In the future, this will be extended to provide more information.
    resource error {
		trace: func() -> string;
  	}
    
    /// A connection to a sql store.
    resource connection {
        open: static func(name: string) -> result<connection, error>;
    }
}
```

**Comment by thomastaylor312** [comment]
Hey @LUK3ARK, thanks for the additional example. Give us just a sec to circle the wagons. A bunch of us are knee deep in 1.0 work right now but I’ll try to get you a clear answer as to how we’re going to fix it and workarounds by tomorrow hopefully

**Comment by vados-cosmonic** [comment]
Hi @LUK3ARK please see my previous comment:

> @LUK3ARK Resource support is lacking in provider bindgen right now -- I assume that the thing you're trying to implement must use a resource, is that correct?

What you can do in the meantime is to use a pseudo-resource approach:

```wit
interface readwrite {
    use types.{statement, row, error, connection};
    /// Pseudo resource that identifies a created connection
    type connection-id = u32;
    /// Pseudo resource that identifies a prepared statement
    type statement-id = u32;
    
    /// query is optimized for querying data, and 
    /// implementors can make use of that fact to optimize 
    /// the performance of query execution (e.g., using
    /// indexes).
    query: func(c: connection-id, q: statement-id) -> result<list<row>, error>;
    
    /// exec is for modifying data in the database.
    exec: func(c: connection-id, q: statement-id) -> result<u32, error>;
    
    prepare_statement: func(func(query: string, params: list<string>) -> result<statement-id, error>
    
    open_connection: func(name: string) -> result<connection-id, error>;   
}
```

This should unblock you for now, as we work on resource support in bindgen.

**Comment by LUK3ARK** [comment]
Thank you for the replies.

I get the error:
 invalid character in identifier '_'
 
I fixed the wit definition to this:

```wit

interface readwrite {
    use types.{statement, row, error, connection};
    /// Pseudo resource that identifies a created connection
    type connection-id = u32;
    /// Pseudo resource that identifies a prepared statement
    type statement-id = u32;
    
    /// query is optimized for querying data, and 
    /// implementors can make use of that fact to optimize 
    /// the performance of query execution (e.g., using
    /// indexes).
    query: func(c: connection-id, q: statement-id) -> result<list<row>, error>;
    
    /// exec is for modifying data in the database.
    exec: func(c: connection-id, q: statement-id) -> result<u32, error>;
    
    prepare-statement: func(query: string, params: list<string>) -> result<statement-id, error>;
    
    open-connection: func(name: string) -> result<connection-id, error>;   
}
```


After making these changes I still get the error:
help: message: `"static_statement.prepare"` is not a valid identifier

I have tried on v0.17 v0.19.2 and v0.20 of wit-bindgen all are no luck

**Comment by vados-cosmonic** [comment]
Awesome to hear @LUK3ARK , thanks for reworking it, I've fixed the underscores in my own comment as well. Thanks for working around this -- resources are awesome, but operations on them aren't QUITE ready to fly over the lattice just yet.

**Comment by LUK3ARK** [comment]
12 |   wasmcloud_provider_wit_bindgen::generate!({
   |  _^
13 | |     impl_struct: Sql,
14 | |     contract: "org:sql",
15 | |     wit_bindgen_cfg: "provider-sql-client"
16 | | });
   | |__^ variant or associated item not found in `InvocationError`
   
   Still getting this error come from the macro

**Comment by thomastaylor312** [comment]
I'm not sure if it will impact it or not, but we have wit bindgen on 0.17 right now in our wasmcloud deps

**Comment by LUK3ARK** [comment]
I have tried 0.17, 0.19.2 and the new 0.2 but that seems very breaking, all result in same

**Comment by LUK3ARK** [comment]
Got a fix for this, I changed my dependency and ran cargo update and got this working:
wasmcloud-provider-wit-bindgen = { git = "https://github.com/wasmCloud/wasmCloud.git", rev = "5a3a37af8c4051989e0fcc9c965668a7a7d0599f" }

I tried this with my original setup in hopes this was the original cause of that but I still had issues building. When applying @vados-cosmonic suggested changes and moved to the specific revision I was able to compile my provider.

This removes my blocker
