### ISSUE TITLE
[BUG] Can't get response without finishing body

### ISSUE THREAD

**Issue by peter-jerry-ye** [wasmCloud/wasmCloud#2624]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [X] wasmCloud host
- [ ] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

A http response is not finished until the response body is finished explicitly

### Steps to reproduce

1. Create a new project with `wash new component hello-ts --template-name hello-world-typescript`
2. Comment line 26 and 32 in `http-hello-world.ts` (i.e. do not finish outgoingbody or dispose stream explicitly)
3. `pnpm i && wash build`
4. `curl localhost:8080`

### Expected behavior

I expected to see it prints `Hello from Typescript!` and curl finishes, but it prints and then waits indefinitely.

### Environment

- OS: MacOS
- Shell: zsh
- wasmcloud Version: `wash --version` gives me `wash 0.29.2`, `wash ui` shows `1.0.4`

### Screenshots / Logs / Additional context

Notice that if I serve the exact same wasm with `wasmtime serve ./build/http_hello_world_s.wasm`, the behaviour is different in that the curl command finishes normally. I have wasmtime 22.0.0 and 23.0.1 tested.

**Comment by vados-cosmonic** [comment]
Hey @peter-jerry-ye thanks for finding this discrepancy -- I tried it myself and was able to easily reproduce with the steps you laid out! Just spent some time digging into it and I think there must be some differences in our implementations of the wasi_http host implementations we use.

Trying to find the difference in implementations between how serve is using `wasmtime_wasi_http` and how we are -- and I found some things but I did have one question:

Did you find that you got `Hello from Typescript!` *once* with the wasmCloud host, and then the subsequent calls hung?

From code on `main` I'm finding that I get the expected response *once*, then subsequent calls hang.

**Comment by brooksmtownsend** [comment]
> From code on main I'm finding that I get the expected response once, then subsequent calls hang.

☝🏻 this is actually due to a bug that we've fixed in our handling of wRPC asynchronous streams, and should be fixed by updating the http-server version to `0.22.0` in your wadm manifest.

**Comment by vados-cosmonic** [comment]
Ah thanks! Going to update the codebase and put up a little PR to move that forward!

**Comment by vados-cosmonic** [comment]
Hey @peter-jerry-ye so it turns out the bug that @brooksmtownsend noted above is exactly the fix you want!

While it's generally a good idea to clean up resources -- `wasmcloud` will also work similarly to `wasmtime` and handle the requests!

PR #2628 will update all the examples to use v0.22.0 of the HTTP server provider so this problem should not happen in the future!

In your local `wadm.yaml` if you change the `0.21.0` to `0.22.0` you should be able to test and confirm as well :)

**Comment by peter-jerry-ye** [comment]
@vados-cosmonic @brooksmtownsend Sorry for the late reply

> Did you find that you got Hello from Typescript! once with the wasmCloud host, and then the subsequent calls hung?

Yes, that's what I've found

> ☝🏻 this is actually due to a bug that we've fixed in our handling of wRPC asynchronous streams, and should be fixed by updating the http-server version to 0.22.0 in your wadm manifest.

I tried but it seems that the problem still exists. I'm not sure if you can reproduce it?

> While it's generally a good idea to clean up resources -- wasmcloud will also work similarly to wasmtime and handle the requests!

I wonder if the expected behavior should be clarified by the `wasi-http`? Or it's up to the implementors?

**Comment by peter-jerry-ye** [comment]
Also I have a small suggestion. Can we have `wash version` command to print all the version information, including `wadm` `nats` `wash` and maybe the versions of running providers so that we can report all the necessary version information? Or maybe displaying the version of providers in `wash ui`?

**Comment by vados-cosmonic** [comment]
Hey @peter-jerry-ye

**Comment by vados-cosmonic** [comment]
oh and also to clarify 

> I wonder if the expected behavior should be clarified by the wasi-http? Or it's up to the implementors?

Yes, it's a bit hard to find but `wasi-http` is written such that you are expected to drop the [outgoing stream or call `finish`](https://github.com/WebAssembly/wasi-http/blob/main/wit/types.wit#L599). Input streams also work this way.

It depends on the language of course (if you know your language will drop in the right order) but in general ensuring that you use it correctly is important.

**Comment by peter-jerry-ye** [comment]
Hi @vados-cosmonic 

> did you try deleting and redeploying the app after updating the manifest?

Yes I tried. I'm not sure if there's other command that can gives a fresh wasmCloud instance, but from the log

> 2024-07-31T02:51:25.006704Z  INFO wasmcloud_host::wasmbus: provider started provider_ref="ghcr.io/wasmcloud/http-server:0.22.0" provider_id="typescript_hello_world-httpserver"

It does seem that it has been updated.

> This would be a great idea! would you mind making a new issue for this? Would be a nice feature to have in `wash`

Created #2642.

> Yes, it's a bit hard to find but wasi-http is written such that you are expected to drop the [outgoing stream or call finish](https://github.com/WebAssembly/wasi-http/blob/main/wit/types.wit#L599). Input streams also work this way.

Yes, but in this case I'm not calling finish of the response_body either, so I'm not sure if that is the correct behavior. However wasmtime allows it.

**Comment by vados-cosmonic** [comment]
Don't know if this is fixed yet, but we should check before we let stalebot mark it completed!

**Comment by vados-cosmonic** [comment]
Just confirmed this issue is still present -- with the lines removed, we hang on trying to serve the HTTP request

**Comment by peter-jerry-ye** [comment]
@vados-cosmonic Thank you for the confirmation. I wonder if it's related to how the resources are handled through rpc, i.e. if a component is finished no extra messages would be sent?
