### ISSUE TITLE
[BUG] build failed with 1.227.1  wasm-tools

### ISSUE THREAD

**Issue by Patrick0308** [wasmCloud/wasmCloud#4207]
### Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

### Describe the bug

while update wasm-tools to 1.227.1 version from 1.220.0 , wash build failed

```
traffic-collector (main*) » wash build                                                                                                                  ~/projects/traffic-collector 130 ↵ 
# github.com/Patrick0308/traffic-collector
main.go:136:11: query.Query(`INSERT INTO tenant_traffic_usage (tenant_id, timestamp, data_in, data_out, qps, api_qps, version)
                       VALUES (?, ?, ?, ?, ?, ?, ?)`, paramList) (no value) used as value
main.go:286:30: runtime.Get("tenant-mapping") (no value) used as value or type
main.go:296:22: runtime.Get("step") (no value) used as value or type
main.go:304:30: runtime.Get("data-in-metric") (no value) used as value or type
main.go:307:31: runtime.Get("data-out-metric") (no value) used as value or type
main.go:310:30: runtime.Get("api-qps-metric") (no value) used as value or type
main.go:313:27: runtime.Get("qps-metric") (no value) used as value or type
main.go:316:32: runtime.Get("metrics-address") (no value) used as value or type

Compiling component failed: exit status: 1
traffic-collector (main*) » wasm-tools --version                                                                                                          ~/projects/traffic-collector 1 ↵ 
wasm-tools 1.227.1
```

### Steps to reproduce

update wasm-tools to 1.227.1

### Expected behavior

build successful

### Environment

- OS: MacOS
- Shell: zsh
- wasmcloud Version: v1.6.1

**Comment by thomastaylor312** [comment]
Thanks for filing this @Patrick0308! So this is actually a known issue (see [here](https://github.com/wasmCloud/go/pull/228)). You need to use <=1.225 for now. But what it made me realize is that we should probably add this warning in the main Go docs as well and not just in the examples.

@vados-cosmonic before I go add something to the docs, is this just temporary (as in, should be fixed in the next few weeks) or is it going to be a bit and we should add the warnings to the docs?

**Comment by vados-cosmonic** [comment]
Hey @thomastaylor312 can we move this to wasmcloud/go? Also, absolutely the [warning in the postgres example](https://github.com/wasmCloud/go/tree/main/examples/component/sqldb-postgres-query#-dependencies) applies here, it's temporary and [*not yet fixed*](https://github.com/bytecodealliance/go-modules/issues/297) (another issue seems to have popped up with 227.1.

We need to stay on <= 1.225 for now like you said IMO
